### ISSUE TITLE
SVM error

### ISSUE THREAD

**Issue by EvergreenHZ** [Ekberjan/Face-Verification#1]
I am trying to transplant your code to my Ubuntu 16.04, OpenCV 3.3.0, sadly, I come across the type error: "CvSVM does not name a type". I checked some information and found that my OpenCV has moved SVM to cv::ml namespace, and I do not know how to fix the problem. Please Help me.

**Comment by Ekberjan** [comment]
Please downgrade your OpenCV version to such as 2.4.10, or change relevant part of the code to meet your version.
