### ISSUE TITLE
what are negative and positive samples for svm trainning

### ISSUE THREAD

**Issue by EvergreenHZ** [Ekberjan/Face-Verification#2]
Actually, I don't know what are the neg and pos samples for your svm training. It seems that you detect the face and get lbph features and put them into svm. But what you want to do is verification, which means you'll get two faces as input and judge weather they are the same people.

**Comment by Ekberjan** [comment]
As I described clearly in the README.md:

`You need to provide relevant negative images for training SVM. Currently, the negative image count is set as 300, you can change it in the code according to your own case. You need to provide negative image list txt file. Please refer to negativeImageList member in the faceverifier.cpp file for more information. For generating negative image list, you can copy your negative images to the folder Release/Negative_Images/, then double click getFileList.bat, it will generate a txt file containing your negative image list. Provide this txt file as your negativeImageList in faceverifier.cpp.`
